title: Ali Hasnain Khowaja
description: Aerospace Engineer
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Collections
collections:
  primer:            # <-- renamed from 'topics'
    output: true
    permalink: /primer/:name/
  projects:
    output: true
    permalink: /projects/:name/
